version: '3'
networks:
  net:
    driver: bridge

services:
  # mongo:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: Bechallengers
  #     MONGO_INITDB_ROOT_PASSWORD: FsCkbE2PkhNM8rw0
  #     MONGO_INITDB_DATABASE: nest
  #     MONGO_URI: ${{ secrets.MONGODB_URI }}
  #   networks:
  #     net:
  #       aliases:
  #         - mongo

  # # elasticsearch:
  # #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
  # #   environment:
  # #     ELASTIC_USERNAME: ${{ secrets.ELASTICSEARCH_USERNAME }}
  # #     ELASTIC_PASSWORD: ${{ secrets.ELASTICSEARCH_PASSWORD }}
  # #     ELASTICSEARCH_NODE: ${{ secrets.ELASTICSEARCH_NODE }}
  # #     discovery.seed_hosts: elasticsearch
  # #     cluster.initial_master_nodes: elasticsearch
  # #   networks:
  # #     net:
  # #       aliases:
  # #         - elasticsearch
  # #   depends_on:
  # #     - mongo


  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: ${{ secrets.MONGODB_URI }}
      ELASTICSEARCH_NODE: ${{ secrets.ELASTICSEARCH_NODE }}

    # depends_on:
    #   - mongo
      # - elasticsearch

    networks:
      net:
        aliases:
          - backend
