# MongoDB connection string
mongo-url = "mongodb+srv://Bechallengers:FsCkbE2PkhNM8rw0@amuwiki.nhurd.mongodb.net/?retryWrites=true&w=majority"


# Elasticsearch connection information
elasticsearch-urls = ["https://amuwiki.es.ap-northeast-2.aws.elastic-cloud.com"]
elasticsearch-user = "elastic" 
elasticsearch-password = "dZFevGqIi9NsjeniWcL25kNW"



direct-read-namespaces = ["nest.amuwikis"]
change-stream-namespaces = ["nest.amuwikis"]







