# MongoDB connection string
mongo-url = "mongodb+srv://sparta:wy2K1r5YENz7v2Jh@amuwiki.ldisv.mongodb.net/nest?retryWrites=true&w=majority"


# Elasticsearch connection information
elasticsearch-urls = ["https://amuwiki.es.asia-northeast3.gcp.elastic-cloud.com"]
elasticsearch-user = "elastic" 
elasticsearch-password = "g1AEszxYkfJTiJZ5tXCZvNu9"



direct-read-namespaces = ["nest.amuwikis"]
change-stream-namespaces = ["nest.amuwikis"]







