name: Build and Deploy Docker Image

on:
  push: 
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
            node-version: '17'
      - name: Generate Environment Variables File for Production
        run: |
            echo "PORT=$PORT" >> .env
            echo "MONGODB_URI=$MONGODB_URI" >> .env
            echo "ELASTICSEARCH_NODE=$ELASTICSEARCH_NODE" >> .env
            echo "ELASTICSEARCH_USERNAME=$ELASTICSEARCH_USERNAME" >> .env
            echo "ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD" >> .env
            echo "ACCESS_TOKEN_PRIVATE_KEY=$ACCESS_TOKEN_PRIVATE_KEY" >> .env
            echo "NODEMAILER_USERNAME=$NODEMAILER_USERNAME" >> .env
            echo "NODEMAILER_PASSWORD=$NODEMAILER_PASSWORD" >> .env
            echo "STRINGCODE=$STRINGCODE" >> .env
            echo "SUBSTRINGCODE1=$SUBSTRINGCODE1" >> .env
            echo "SUBSTRINGCODE2=$SUBSTRINGCODE2" >> .env
        env:
            PORT: ${{ secrets.REACT_APP_DOMAIN }}
            MONGODB_URI: ${{ secrets.REACT_APP_DOMAIN }}
            ELASTICSEARCH_NODE: ${{ secrets.REACT_APP_DOMAIN }}
            ELASTICSEARCH_USERNAME: ${{ secrets.REACT_APP_DOMAIN }}
            ELASTICSEARCH_PASSWORD: ${{ secrets.REACT_APP_DOMAIN }}
            ACCESS_TOKEN_PRIVATE_KEY: ${{ secrets.REACT_APP_DOMAIN }}
            NODEMAILER_USERNAME: ${{ secrets.REACT_APP_DOMAIN }}
            NODEMAILER_PASSWORD: ${{ secrets.REACT_APP_DOMAIN }}
            STRINGCODE: ${{ secrets.REACT_APP_DOMAIN }}
            SUBSTRINGCODE1: ${{ secrets.REACT_APP_DOMAIN }}
            SUBSTRINGCODE2: ${{ secrets.REACT_APP_DOMAIN }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lkw9/amu:v1.0
      
      - name: SSH to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            docker pull lkw9/amu:v1.0
            docker-compose up --build
