name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run:
                  docker build -f Dockerfile -t myimage .
                  
  docker:
        name: Deploy Docker Image
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v3
           
            - uses: actions/setup-node@v3
              with:
                    node-version: '16'
           
            - name: Generate Environment Variables File for Production
              run: |
                   echo "DB_USER=$DB_USER" >> .env
                   echo "DB_DATABASE=$DB_DATABASE" >> .env
                   echo "DB_PW=$DB_PW" >> .env
                   echo "HOST=$HOST" >> .env
                   echo "PORT=$PORT" >> .env
                   echo "ACCESS_TOKEN_PRIVATE_KEY=$ACCESS_TOKEN_PRIVATE_KEY" >> .env
              env:
                   DB_USER: ${{ secrets.DB_USER }}
                   DB_DATABASE: ${{ secrets.DB_DATABASE }}
                   DB_PW: ${{ secrets.DB_PW }}
                   HOST: ${{ secrets.HOST }}
                   PORT: ${{ secrets.PORT }}
                   ACCESS_TOKEN_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN_PRIVATE_KEY }}
                  
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ${{secrets.DOCKERHUB_USERNAME}}/clone:v1.0
